@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Builder {
  - pathToStorage: Path
  - storageIndex: StorageIndex<?>
  - collectionApi: CollectionApi
  - objectApi: ObjectApi
}
entity Idx << record >> {
  - value: int
}
entity Key << record >> {
  - value: String
}
class ListEntry {
  - path: Path
  - refreshLock: Lock
  - schema: String
  - valid: boolean
  - id: StorageId
  - uriProperties: Set<UriProperty>
  - uri: URI
  - objectApi: ObjectApi
  - name: String
  - collectionApi: CollectionApi
}
class MapEntry {
  - path: Path
  - collectionApi: CollectionApi
  - schema: String
  - objectApi: ObjectApi
  - name: String
  - uri: URI
  - valid: boolean
  - id: StorageId
  - refreshLock: Lock
  - uriProperties: Set<UriProperty>
}
entity Multi << record >> {
  - head: long
}
class ObjectEntry {
  - refreshLock: Lock
  - typeName: String
  - id: StorageId
  - path: Path
  - valid: boolean
  - versioning: Versioning
  - storageIndex: WeakReference<StorageIndex<?>>
  - uuid: String
  - scopedEntries: Set<ScopedEntry>
  - uri: URI
  - uriProperties: Set<UriProperty>
  - log: Logger
}
interface ScopedEntry << interface >>
class ScopedListEntry {
  - scopeUri: URI
}
class ScopedMapEntry {
  - scopeUri: URI
}
class ScopedObjectEntry {
  - scopeUri: URI
}
interface Segment << interface >>
class SequenceEntry {
  - current: long
  - schema: String
  - collectionApi: CollectionApi
  - name: String
  - uri: URI
  - id: StorageId
  - valid: boolean
  - log: Logger
  - path: Path
}
entity Single << record >>
interface StorageEntry << interface >>
class StorageEntryFactory {
  - storageIndex: StorageIndex<?>
  - objectApi: ObjectApi
  + STORED_MAP_MARKER: String
  - pathToStorage: Path
  + STORED_SEQ_MARKER: String
  - collectionApi: CollectionApi
  - log: Logger
  - id: StorageId
  + STORED_LIST_MARKER: String
  + STORED_REF_MARKER: String
}
class UriProperty {
  + segments: Segment[]
  + uri: URI
  + OWN: String
  + position: int
}
interface Versioning << interface >>

Builder              +-[#820000,plain]-  StorageEntryFactory 
Builder              -[#595959,dashed]->  StorageEntryFactory : "«create»"
Idx                  +-[#820000,plain]-  Segment             
Idx                  -[#008200,dashed]-^  Segment             
Key                  +-[#820000,plain]-  Segment             
Key                  -[#008200,dashed]-^  Segment             
ListEntry            -[#595959,dashed]->  Segment             : "«create»"
ListEntry            -[#008200,dashed]-^  StorageEntry        
ListEntry           "1" *-[#595959,plain]-> "uriProperties\n*" UriProperty         
MapEntry             -[#595959,dashed]->  Segment             : "«create»"
MapEntry             -[#008200,dashed]-^  StorageEntry        
MapEntry            "1" *-[#595959,plain]-> "uriProperties\n*" UriProperty         
Multi                -[#008200,dashed]-^  Versioning          
Multi                +-[#820000,plain]-  Versioning          
ObjectEntry          -[#595959,dashed]->  Multi               : "«create»"
ObjectEntry         "1" *-[#595959,plain]-> "scopedEntries\n*" ScopedEntry         
ObjectEntry          -[#595959,dashed]->  Segment             : "«create»"
ObjectEntry          -[#595959,dashed]->  Single              : "«create»"
ObjectEntry          -[#008200,dashed]-^  StorageEntry        
ObjectEntry         "1" *-[#595959,plain]-> "uriProperties\n*" UriProperty         
ObjectEntry         "1" *-[#595959,plain]-> "versioning\n1" Versioning          
ScopedListEntry      -[#000082,plain]-^  ListEntry           
ScopedListEntry      -[#008200,dashed]-^  ScopedEntry         
ScopedListEntry      -[#008200,dashed]-^  StorageEntry        
ScopedMapEntry       -[#000082,plain]-^  MapEntry            
ScopedMapEntry       -[#008200,dashed]-^  ScopedEntry         
ScopedMapEntry       -[#008200,dashed]-^  StorageEntry        
ScopedObjectEntry    -[#000082,plain]-^  ObjectEntry         
ScopedObjectEntry    -[#008200,dashed]-^  ScopedEntry         
ScopedObjectEntry    -[#008200,dashed]-^  StorageEntry        
Segment              -[#595959,dashed]->  Idx                 : "«create»"
Segment              -[#595959,dashed]->  Key                 : "«create»"
Segment              +-[#820000,plain]-  UriProperty         
SequenceEntry        -[#008200,dashed]-^  StorageEntry        
Single               +-[#820000,plain]-  Versioning          
Single               -[#008200,dashed]-^  Versioning          
StorageEntryFactory  -[#595959,dashed]->  Builder             : "«create»"
StorageEntryFactory  -[#595959,dashed]->  ListEntry           : "«create»"
StorageEntryFactory  -[#595959,dashed]->  MapEntry            : "«create»"
StorageEntryFactory  -[#595959,dashed]->  ObjectEntry         : "«create»"
StorageEntryFactory  -[#595959,dashed]->  ScopedListEntry     : "«create»"
StorageEntryFactory  -[#595959,dashed]->  ScopedMapEntry      : "«create»"
StorageEntryFactory  -[#595959,dashed]->  ScopedObjectEntry   : "«create»"
StorageEntryFactory  -[#595959,dashed]->  SequenceEntry       : "«create»"
UriProperty         "1" *-[#595959,plain]-> "segments\n*" Segment             
UriProperty          -[#595959,dashed]->  Segment             : "«create»"
Versioning           +-[#820000,plain]-  ObjectEntry         
@enduml
