package com.aestallon.storageexplorer.swing.ui.dialog.umlexportsettings;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;
import com.aestallon.storageexplorer.client.userconfig.model.UmlExportSettings;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

public class UmlExportSettingsDialog extends JDialog {
  private JPanel contentPane;
  private JButton buttonOK;
  private JButton buttonCancel;
  private JButton buttonApply;
  private JCheckBox checkBoxDetailComplexProps;
  private JCheckBox checkBoxDrawEdgesFromProps;
  private JCheckBox checkBoxLabelEdges;
  private JCheckBox checkBoxDIsplayArity;

  private final UmlExportSettingsController controller;

  public UmlExportSettingsDialog(UmlExportSettingsController controller) {
    this.controller = controller;

    final var initialModel = controller.initialModel();
    checkBoxDetailComplexProps.setSelected(initialModel.isDetailComplexProps());
    checkBoxDrawEdgesFromProps.setSelected(initialModel.isDrawEdgesFromProperty());
    checkBoxLabelEdges.setSelected(initialModel.isLabelEdges());
    checkBoxDIsplayArity.setSelected(initialModel.isDisplayArity());

    setTitle("UML Export Settings");
    setPreferredSize(new Dimension(700, 700));

    setContentPane(contentPane);
    setModal(true);
    getRootPane().setDefaultButton(buttonOK);

    buttonOK.addActionListener(e -> onOK());

    buttonCancel.addActionListener(e -> onCancel());

    buttonApply.addActionListener(e -> onApply());

    // call onCancel() when cross is clicked
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e) {
        onCancel();
      }
    });

    // call onCancel() on ESCAPE
    contentPane.registerKeyboardAction(e -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
        JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
  }

  private void onApply() {
    final boolean detailComplexProps = checkBoxDetailComplexProps.isSelected();
    final boolean drawEdgesFromProps = checkBoxDrawEdgesFromProps.isSelected();
    final boolean labelEdges = checkBoxLabelEdges.isSelected();
    final boolean displayArity = checkBoxDIsplayArity.isSelected();

    final UmlExportSettings settings = new UmlExportSettings();
    settings.setDetailComplexProps(detailComplexProps);
    settings.setDrawEdgesFromProperty(drawEdgesFromProps);
    settings.setLabelEdges(labelEdges);
    settings.setDisplayArity(displayArity);

    controller.finish(settings);
  }

  private void onOK() {
    onApply();
    dispose();
  }

  private void onCancel() {
    dispose();
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPane = new JPanel();
    contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    contentPane.add(panel1,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null,
            null, null, 0, false));
    final Spacer spacer1 = new Spacer();
    panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null,
        0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
    panel1.add(panel2,
        new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
            null, 0, false));
    buttonOK = new JButton();
    buttonOK.setText("OK");
    panel2.add(buttonOK, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    buttonCancel = new JButton();
    buttonCancel.setText("Cancel");
    panel2.add(buttonCancel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    buttonApply = new JButton();
    buttonApply.setText("Apply");
    panel2.add(buttonApply, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
    contentPane.add(panel3,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
            null, 0, false));
    checkBoxDetailComplexProps = new JCheckBox();
    checkBoxDetailComplexProps.setSelected(true);
    checkBoxDetailComplexProps.setText(
        "<HTML><H3>Detail Complex Properties</H4>\n\n<P><EM>Complex properties (such as embedded objects, a.k.a details) should be displayed as separate sub-entities, with a composition relation drawn from the parent entity.</EM></P></HTML>"); //NON-NLS
    panel3.add(checkBoxDetailComplexProps,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    checkBoxDrawEdgesFromProps = new JCheckBox();
    checkBoxDrawEdgesFromProps.setText(
        "<HTML><H3>Draw Edges from Source Properties</H3>\n\n<P><EM>If ticked, edges representing relations (dependency, composition etc.) are drawn from the position where the corresponding property is displayed on the host entity.</EM></P>\n\n<P><EM>If unticked, edges are drawn as appropriate.</EM></P></HTML>");
    panel3.add(checkBoxDrawEdgesFromProps,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    checkBoxLabelEdges = new JCheckBox();
    checkBoxLabelEdges.setText(
        "<HTML>   <H3>Label Edges</H3>      <P><EM>If ticked, edges are labeled with the name of the originating property. If <CODE>Detail Complex Properties</CODE> is not ticked, the label will contain the full property path on the host entity defining the relation.</EM></P> </HTML>");
    panel3.add(checkBoxLabelEdges,
        new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    checkBoxDIsplayArity = new JCheckBox();
    checkBoxDIsplayArity.setText(
        "<HTML>\n  <H3>Display Arity</H3>\n  \n  <P><EM>If ticked, edges endpoints are labeled with <CODE>1</CODE> and <CODE>*</CODE> to denote one-to-one and one-to-many relations.</EM></P>\n</HTML>");
    panel3.add(checkBoxDIsplayArity,
        new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {return contentPane;}

}
