#!/usr/bin/env node

// Reads the centralised version number from the root gradle.properties file (the single source
// of truth for the whole project, see CLAUDE.md) and emits it as a TypeScript module so the
// Angular app can display it without hardcoding a copy that can drift out of sync.

const fs = require('fs');
const path = require('path');

const gradlePropertiesFile = path.resolve(__dirname, '..', '..', 'gradle.properties');

const outputFile = path.resolve(__dirname, '..', 'src', 'app', 'version.ts');

const gradleSource = fs.readFileSync(gradlePropertiesFile, 'utf8');
const match = gradleSource.match(/^\s*version\s*=\s*(.+?)\s*$/m);
if (!match) {
  throw new Error(`Could not find a "version=..." declaration in ${gradlePropertiesFile}`);
}

const version = match[1];
const contents = `// AUTO-GENERATED by scripts/generate-version.js — do not edit, do not commit.
export const VERSION_NUMBER = '${version}';
`;

fs.writeFileSync(outputFile, contents);
console.log(`Wrote ${outputFile} (VERSION_NUMBER = '${version}')`);
